#!/usr/bin/env bash

mkdir -p /home/demo/ratings/

###########
# old C5.8 syntax
#CREATE TABLE `streaming_user_ratings` (movieid INT,userid INT,rating INT,movietitle STRING)
#DISTRIBUTE BY HASH (movieid) INTO 4 BUCKETS
#TBLPROPERTIES(
#  'storage_handler' = 'com.cloudera.kudu.hive.KuduStorageHandler',
#  'kudu.table_name' = 'streaming_user_ratings',
#  'kudu.master_addresses' = 'quickstart.cloudera:7051',
#  'kudu.key_columns' = 'movieid, userid'
#);
#############


#new syntax
impala-shell -i localhost -d default -q "CREATE TABLE `streaming_user_ratings` (
movieid INT,
userid INT,
rating INT,
movietitle STRING,
PRIMARY KEY(movieid, userid)
)
PARTITION BY HASH(movieid)
PARTITIONS 4 STORED AS KUDU;"

